version: '3.8'

services:
  bot:
    build: .
    # ports:
    #   - "5000:5000"
    command: python main.py
    expose:
      - 81
    volumes:
      - ./app:/app/
    environment:
      - SERVER_HOST=mysqldb_mariadb_1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=wsp.diego-luque.com
      - LETSENCRYPT_HOST=wsp.diego-luque.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bot

networks:
  default:
    name: web_private_red_webapps #dbs_red_db
    external: true
